version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: devhub-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: yatharth
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: devhub_db
    ports:
      - "5432:5432"
    volumes:
      - devhub_pg_data:/var/lib/postgresql/data

volumes:
  devhub_pg_data:

